ctf:
  name: KosenCTF
  start_at: 2019-01-01 00:00:00 +09:00
  end_at: 2020-01-01 00:00:00 +09:00
  score_expr: "max(200, (V*V) / (V + (V/10) * (0 if N == 1 else N)))"
  admin:
    name: "admin"
    password: "password"
