version: '3'
services:
    kosenctfkit_db:
        image: postgres:10.6-alpine
        environment:
          - POSTGRES_USER=kosenctfkit
          - POSTGRES_PASSWORD=kosenctfkit
          - POSTGRES_DB=kosenctfkit
          - POSTGRES_INITDB_ARGS=--encoding=UTF-8
        volumes:
          - ./database:/var/lib/postgresql/data
    kosenctfkit:
        build: ./
        restart: always
        depends_on:
            - kosenctfkit_db
        volumes:
            - ./challenges:/app/challenges
            - ./ctf_config.yaml:/app/ctf_config.yaml
            - ./config.py:/app/config.py
        command: >
            sh -c "
            python3 manage.py init &&
            python3 manage.py challenge add --all &&
            gunicorn app:app -b 0.0.0.0:5000 --worker-class=gevent --worker-connections=500 --workers=3"
    nginx:
        build: ./nginx/
        ports:
            - 80:80
        volumes:
            - ./accesslog:/var/log/nginx/
        depends_on:
            - kosenctfkit



