version: '3'
services:
    kosenctfkit_db:
        image: mysql:8
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: kosenctfkit
          MYSQL_USER: kosenctfkit
          MYSQL_PASSWORD: kosenctfkit
        volumes:
            - ./database:/var/lib/mysql
    kosenctfkit:
        build: ./
        restart: always
        depends_on:
            - kosenctfkit_db
        ports:
            - 4000:5000
        volumes:
            - ./challenges:/app/challenges
            - ./ctf_config.yaml:/app/ctf_config.yaml
            - ./config.py:/app/config.py
        command: >
            sh -c "
            python3 manage.py init ctf_config.yaml &&
            python3 manage.py challenge add --all &&
            gunicorn app:app -b 0.0.0.0:5000"


